// Code generated by protoc-gen-go. DO NOT EDIT.
// source: DbService.proto

package com_yue_dbservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// get
type GetRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Paras                string   `protobuf:"bytes,3,opt,name=paras,proto3" json:"paras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *GetRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *GetRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

type GetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// getOne
type GetOneRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Paras                string   `protobuf:"bytes,4,opt,name=paras,proto3" json:"paras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneRequest) Reset()         { *m = GetOneRequest{} }
func (m *GetOneRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneRequest) ProtoMessage()    {}
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{2}
}
func (m *GetOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneRequest.Unmarshal(m, b)
}
func (m *GetOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneRequest.Marshal(b, m, deterministic)
}
func (dst *GetOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneRequest.Merge(dst, src)
}
func (m *GetOneRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneRequest.Size(m)
}
func (m *GetOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneRequest proto.InternalMessageInfo

func (m *GetOneRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *GetOneRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *GetOneRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *GetOneRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

type GetOneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneResponse) Reset()         { *m = GetOneResponse{} }
func (m *GetOneResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneResponse) ProtoMessage()    {}
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{3}
}
func (m *GetOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResponse.Unmarshal(m, b)
}
func (m *GetOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResponse.Marshal(b, m, deterministic)
}
func (dst *GetOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResponse.Merge(dst, src)
}
func (m *GetOneResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneResponse.Size(m)
}
func (m *GetOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResponse proto.InternalMessageInfo

func (m *GetOneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// list
type ListRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{4}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *ListRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ListRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

type ListResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{5}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// save
type SaveRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Paras                string   `protobuf:"bytes,4,opt,name=paras,proto3" json:"paras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{6}
}
func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (dst *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(dst, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *SaveRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SaveRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *SaveRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

type SaveResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{7}
}
func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (dst *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(dst, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// update
type UpdateRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Paras                string   `protobuf:"bytes,4,opt,name=paras,proto3" json:"paras,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{8}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *UpdateRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *UpdateRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *UpdateRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

type UpdateResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{9}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// del
type DelRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelRequest) Reset()         { *m = DelRequest{} }
func (m *DelRequest) String() string { return proto.CompactTextString(m) }
func (*DelRequest) ProtoMessage()    {}
func (*DelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{10}
}
func (m *DelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelRequest.Unmarshal(m, b)
}
func (m *DelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelRequest.Marshal(b, m, deterministic)
}
func (dst *DelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelRequest.Merge(dst, src)
}
func (m *DelRequest) XXX_Size() int {
	return xxx_messageInfo_DelRequest.Size(m)
}
func (m *DelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DelRequest proto.InternalMessageInfo

func (m *DelRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *DelRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *DelRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DelResponse struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DelResponse) Reset()         { *m = DelResponse{} }
func (m *DelResponse) String() string { return proto.CompactTextString(m) }
func (*DelResponse) ProtoMessage()    {}
func (*DelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{11}
}
func (m *DelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelResponse.Unmarshal(m, b)
}
func (m *DelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelResponse.Marshal(b, m, deterministic)
}
func (dst *DelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelResponse.Merge(dst, src)
}
func (m *DelResponse) XXX_Size() int {
	return xxx_messageInfo_DelResponse.Size(m)
}
func (m *DelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DelResponse proto.InternalMessageInfo

func (m *DelResponse) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

// multiGet
type MultiGetRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Field                string   `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetRequest) Reset()         { *m = MultiGetRequest{} }
func (m *MultiGetRequest) String() string { return proto.CompactTextString(m) }
func (*MultiGetRequest) ProtoMessage()    {}
func (*MultiGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{12}
}
func (m *MultiGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetRequest.Unmarshal(m, b)
}
func (m *MultiGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetRequest.Marshal(b, m, deterministic)
}
func (dst *MultiGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetRequest.Merge(dst, src)
}
func (m *MultiGetRequest) XXX_Size() int {
	return xxx_messageInfo_MultiGetRequest.Size(m)
}
func (m *MultiGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetRequest proto.InternalMessageInfo

func (m *MultiGetRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *MultiGetRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *MultiGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MultiGetRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type MultiGetResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiGetResponse) Reset()         { *m = MultiGetResponse{} }
func (m *MultiGetResponse) String() string { return proto.CompactTextString(m) }
func (*MultiGetResponse) ProtoMessage()    {}
func (*MultiGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{13}
}
func (m *MultiGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiGetResponse.Unmarshal(m, b)
}
func (m *MultiGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiGetResponse.Marshal(b, m, deterministic)
}
func (dst *MultiGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiGetResponse.Merge(dst, src)
}
func (m *MultiGetResponse) XXX_Size() int {
	return xxx_messageInfo_MultiGetResponse.Size(m)
}
func (m *MultiGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MultiGetResponse proto.InternalMessageInfo

func (m *MultiGetResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// toOne
type ToOneRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Paras                string   `protobuf:"bytes,4,opt,name=paras,proto3" json:"paras,omitempty"`
	Result               string   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToOneRequest) Reset()         { *m = ToOneRequest{} }
func (m *ToOneRequest) String() string { return proto.CompactTextString(m) }
func (*ToOneRequest) ProtoMessage()    {}
func (*ToOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{14}
}
func (m *ToOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToOneRequest.Unmarshal(m, b)
}
func (m *ToOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToOneRequest.Marshal(b, m, deterministic)
}
func (dst *ToOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToOneRequest.Merge(dst, src)
}
func (m *ToOneRequest) XXX_Size() int {
	return xxx_messageInfo_ToOneRequest.Size(m)
}
func (m *ToOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToOneRequest proto.InternalMessageInfo

func (m *ToOneRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *ToOneRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ToOneRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *ToOneRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

func (m *ToOneRequest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ToOneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToOneResponse) Reset()         { *m = ToOneResponse{} }
func (m *ToOneResponse) String() string { return proto.CompactTextString(m) }
func (*ToOneResponse) ProtoMessage()    {}
func (*ToOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{15}
}
func (m *ToOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToOneResponse.Unmarshal(m, b)
}
func (m *ToOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToOneResponse.Marshal(b, m, deterministic)
}
func (dst *ToOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToOneResponse.Merge(dst, src)
}
func (m *ToOneResponse) XXX_Size() int {
	return xxx_messageInfo_ToOneResponse.Size(m)
}
func (m *ToOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToOneResponse proto.InternalMessageInfo

func (m *ToOneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// toMany
type ToManyRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Paras                string   `protobuf:"bytes,4,opt,name=paras,proto3" json:"paras,omitempty"`
	Result               string   `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToManyRequest) Reset()         { *m = ToManyRequest{} }
func (m *ToManyRequest) String() string { return proto.CompactTextString(m) }
func (*ToManyRequest) ProtoMessage()    {}
func (*ToManyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{16}
}
func (m *ToManyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToManyRequest.Unmarshal(m, b)
}
func (m *ToManyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToManyRequest.Marshal(b, m, deterministic)
}
func (dst *ToManyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToManyRequest.Merge(dst, src)
}
func (m *ToManyRequest) XXX_Size() int {
	return xxx_messageInfo_ToManyRequest.Size(m)
}
func (m *ToManyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ToManyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ToManyRequest proto.InternalMessageInfo

func (m *ToManyRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *ToManyRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *ToManyRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *ToManyRequest) GetParas() string {
	if m != nil {
		return m.Paras
	}
	return ""
}

func (m *ToManyRequest) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ToManyResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToManyResponse) Reset()         { *m = ToManyResponse{} }
func (m *ToManyResponse) String() string { return proto.CompactTextString(m) }
func (*ToManyResponse) ProtoMessage()    {}
func (*ToManyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{17}
}
func (m *ToManyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToManyResponse.Unmarshal(m, b)
}
func (m *ToManyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToManyResponse.Marshal(b, m, deterministic)
}
func (dst *ToManyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToManyResponse.Merge(dst, src)
}
func (m *ToManyResponse) XXX_Size() int {
	return xxx_messageInfo_ToManyResponse.Size(m)
}
func (m *ToManyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ToManyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ToManyResponse proto.InternalMessageInfo

func (m *ToManyResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// count
type CountRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{18}
}
func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (dst *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(dst, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

func (m *CountRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *CountRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *CountRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

type CountResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{19}
}
func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (dst *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(dst, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// sum
type SumRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	Field                string   `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{20}
}
func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (dst *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(dst, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *SumRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

func (m *SumRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *SumRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type SumResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{21}
}
func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (dst *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(dst, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// query
type QueryRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
	RawQuery             string   `protobuf:"bytes,2,opt,name=rawQuery,proto3" json:"rawQuery,omitempty"`
	Where                string   `protobuf:"bytes,3,opt,name=where,proto3" json:"where,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryRequest) Reset()         { *m = QueryRequest{} }
func (m *QueryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()    {}
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{22}
}
func (m *QueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryRequest.Unmarshal(m, b)
}
func (m *QueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryRequest.Marshal(b, m, deterministic)
}
func (dst *QueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRequest.Merge(dst, src)
}
func (m *QueryRequest) XXX_Size() int {
	return xxx_messageInfo_QueryRequest.Size(m)
}
func (m *QueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRequest proto.InternalMessageInfo

func (m *QueryRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *QueryRequest) GetRawQuery() string {
	if m != nil {
		return m.RawQuery
	}
	return ""
}

func (m *QueryRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

type QueryResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryResponse) Reset()         { *m = QueryResponse{} }
func (m *QueryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()    {}
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_DbService_a28ebe67626703d9, []int{23}
}
func (m *QueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResponse.Unmarshal(m, b)
}
func (m *QueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResponse.Marshal(b, m, deterministic)
}
func (dst *QueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResponse.Merge(dst, src)
}
func (m *QueryResponse) XXX_Size() int {
	return xxx_messageInfo_QueryResponse.Size(m)
}
func (m *QueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResponse proto.InternalMessageInfo

func (m *QueryResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "com.yue.dbservice.getRequest")
	proto.RegisterType((*GetResponse)(nil), "com.yue.dbservice.getResponse")
	proto.RegisterType((*GetOneRequest)(nil), "com.yue.dbservice.getOneRequest")
	proto.RegisterType((*GetOneResponse)(nil), "com.yue.dbservice.getOneResponse")
	proto.RegisterType((*ListRequest)(nil), "com.yue.dbservice.listRequest")
	proto.RegisterType((*ListResponse)(nil), "com.yue.dbservice.listResponse")
	proto.RegisterType((*SaveRequest)(nil), "com.yue.dbservice.saveRequest")
	proto.RegisterType((*SaveResponse)(nil), "com.yue.dbservice.saveResponse")
	proto.RegisterType((*UpdateRequest)(nil), "com.yue.dbservice.updateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "com.yue.dbservice.updateResponse")
	proto.RegisterType((*DelRequest)(nil), "com.yue.dbservice.delRequest")
	proto.RegisterType((*DelResponse)(nil), "com.yue.dbservice.delResponse")
	proto.RegisterType((*MultiGetRequest)(nil), "com.yue.dbservice.multiGetRequest")
	proto.RegisterType((*MultiGetResponse)(nil), "com.yue.dbservice.multiGetResponse")
	proto.RegisterType((*ToOneRequest)(nil), "com.yue.dbservice.toOneRequest")
	proto.RegisterType((*ToOneResponse)(nil), "com.yue.dbservice.toOneResponse")
	proto.RegisterType((*ToManyRequest)(nil), "com.yue.dbservice.toManyRequest")
	proto.RegisterType((*ToManyResponse)(nil), "com.yue.dbservice.toManyResponse")
	proto.RegisterType((*CountRequest)(nil), "com.yue.dbservice.countRequest")
	proto.RegisterType((*CountResponse)(nil), "com.yue.dbservice.countResponse")
	proto.RegisterType((*SumRequest)(nil), "com.yue.dbservice.sumRequest")
	proto.RegisterType((*SumResponse)(nil), "com.yue.dbservice.sumResponse")
	proto.RegisterType((*QueryRequest)(nil), "com.yue.dbservice.queryRequest")
	proto.RegisterType((*QueryResponse)(nil), "com.yue.dbservice.queryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DbServiceClient is the client API for DbService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DbServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error)
	MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error)
	ToOne(ctx context.Context, in *ToOneRequest, opts ...grpc.CallOption) (*ToOneResponse, error)
	ToMany(ctx context.Context, in *ToManyRequest, opts ...grpc.CallOption) (*ToManyResponse, error)
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
}

type dbServiceClient struct {
	cc *grpc.ClientConn
}

func NewDbServiceClient(cc *grpc.ClientConn) DbServiceClient {
	return &dbServiceClient{cc}
}

func (c *dbServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error) {
	out := new(GetOneResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/getOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Save(ctx context.Context, in *SaveRequest, opts ...grpc.CallOption) (*SaveResponse, error) {
	out := new(SaveResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/save", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Del(ctx context.Context, in *DelRequest, opts ...grpc.CallOption) (*DelResponse, error) {
	out := new(DelResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) MultiGet(ctx context.Context, in *MultiGetRequest, opts ...grpc.CallOption) (*MultiGetResponse, error) {
	out := new(MultiGetResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/multiGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ToOne(ctx context.Context, in *ToOneRequest, opts ...grpc.CallOption) (*ToOneResponse, error) {
	out := new(ToOneResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/toOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) ToMany(ctx context.Context, in *ToManyRequest, opts ...grpc.CallOption) (*ToManyResponse, error) {
	out := new(ToManyResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/toMany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, "/com.yue.dbservice.DbService/query", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServiceServer is the server API for DbService service.
type DbServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetOne(context.Context, *GetOneRequest) (*GetOneResponse, error)
	List(context.Context, *ListRequest) (*ListResponse, error)
	Save(context.Context, *SaveRequest) (*SaveResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Del(context.Context, *DelRequest) (*DelResponse, error)
	MultiGet(context.Context, *MultiGetRequest) (*MultiGetResponse, error)
	ToOne(context.Context, *ToOneRequest) (*ToOneResponse, error)
	ToMany(context.Context, *ToManyRequest) (*ToManyResponse, error)
	Count(context.Context, *CountRequest) (*CountResponse, error)
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
}

func RegisterDbServiceServer(s *grpc.Server, srv DbServiceServer) {
	s.RegisterService(&_DbService_serviceDesc, srv)
}

func _DbService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).GetOne(ctx, req.(*GetOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Save",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Save(ctx, req.(*SaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Del(ctx, req.(*DelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_MultiGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).MultiGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/MultiGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).MultiGet(ctx, req.(*MultiGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ToOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ToOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/ToOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ToOne(ctx, req.(*ToOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_ToMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).ToMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/ToMany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).ToMany(ctx, req.(*ToManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DbService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.yue.dbservice.DbService/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DbService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.yue.dbservice.DbService",
	HandlerType: (*DbServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get",
			Handler:    _DbService_Get_Handler,
		},
		{
			MethodName: "getOne",
			Handler:    _DbService_GetOne_Handler,
		},
		{
			MethodName: "list",
			Handler:    _DbService_List_Handler,
		},
		{
			MethodName: "save",
			Handler:    _DbService_Save_Handler,
		},
		{
			MethodName: "update",
			Handler:    _DbService_Update_Handler,
		},
		{
			MethodName: "del",
			Handler:    _DbService_Del_Handler,
		},
		{
			MethodName: "multiGet",
			Handler:    _DbService_MultiGet_Handler,
		},
		{
			MethodName: "toOne",
			Handler:    _DbService_ToOne_Handler,
		},
		{
			MethodName: "toMany",
			Handler:    _DbService_ToMany_Handler,
		},
		{
			MethodName: "count",
			Handler:    _DbService_Count_Handler,
		},
		{
			MethodName: "sum",
			Handler:    _DbService_Sum_Handler,
		},
		{
			MethodName: "query",
			Handler:    _DbService_Query_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "DbService.proto",
}

func init() { proto.RegisterFile("DbService.proto", fileDescriptor_DbService_a28ebe67626703d9) }

var fileDescriptor_DbService_a28ebe67626703d9 = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x96, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0x93, 0xb4, 0xc9, 0x97, 0x4e, 0x0e, 0xfd, 0x58, 0x21, 0x14, 0x59, 0xa2, 0x84, 0x45,
	0x6d, 0x23, 0x2e, 0x72, 0x01, 0xaf, 0x80, 0x40, 0x48, 0xa0, 0x8a, 0x54, 0x48, 0xc0, 0x15, 0x4e,
	0x3c, 0x04, 0x4b, 0x3e, 0x24, 0xde, 0xdd, 0x56, 0x7d, 0x03, 0x78, 0x18, 0xde, 0x11, 0x79, 0xd7,
	0x87, 0x75, 0x99, 0xc4, 0x48, 0x51, 0xc2, 0xe5, 0xec, 0x4e, 0x66, 0x7e, 0x3b, 0xe3, 0xf9, 0x4f,
	0xe0, 0xf4, 0xd5, 0xfc, 0x1a, 0x93, 0x1b, 0x7f, 0x81, 0xd3, 0x55, 0x12, 0xcb, 0x98, 0x3d, 0x58,
	0xc4, 0xe1, 0xf4, 0x4e, 0xe1, 0xd4, 0x9b, 0x0b, 0x73, 0xc1, 0x3f, 0x01, 0x2c, 0x51, 0xce, 0x70,
	0xad, 0x50, 0x48, 0x76, 0x06, 0xe0, 0xb9, 0xd2, 0xbd, 0x8e, 0x55, 0xb2, 0xc0, 0x51, 0x73, 0xdc,
	0x9c, 0x9c, 0xcc, 0xac, 0x13, 0xf6, 0x10, 0xda, 0xd2, 0x9d, 0x07, 0x38, 0x6a, 0xe9, 0x2b, 0x63,
	0xa4, 0xa7, 0x2b, 0x37, 0x71, 0xc5, 0xe8, 0xc8, 0x9c, 0x6a, 0x83, 0x9f, 0x43, 0x4f, 0x47, 0x16,
	0xab, 0x38, 0x12, 0xc8, 0x1e, 0x41, 0x27, 0x41, 0xa1, 0x02, 0x99, 0x85, 0xcd, 0x2c, 0xbe, 0x86,
	0xc1, 0x12, 0xe5, 0x55, 0x84, 0x3b, 0x33, 0xdc, 0x7e, 0xc7, 0x04, 0x73, 0x06, 0x6d, 0x94, 0x64,
	0xc7, 0x36, 0xd9, 0x04, 0x86, 0x79, 0xca, 0x1a, 0xb8, 0xcf, 0xd0, 0x0b, 0x7c, 0x21, 0xf7, 0x80,
	0xc6, 0x2f, 0xa0, 0x6f, 0x42, 0xd7, 0x20, 0xc4, 0xd0, 0x13, 0xee, 0xcd, 0x01, 0xab, 0x73, 0x01,
	0x7d, 0x93, 0xb0, 0xbe, 0x71, 0x6a, 0xe5, 0xb9, 0xf2, 0xb0, 0x8d, 0xcb, 0x53, 0x92, 0x70, 0xdd,
	0x02, 0x6e, 0x06, 0xe0, 0x61, 0xb0, 0x1b, 0xd9, 0x10, 0x5a, 0xbe, 0x97, 0x61, 0xb5, 0x7c, 0x2f,
	0xfd, 0xa0, 0x75, 0xcc, 0x9a, 0xd4, 0x21, 0x9c, 0x86, 0x2a, 0x90, 0xfe, 0x9b, 0x5d, 0xc7, 0xea,
	0x5e, 0xfe, 0xd4, 0xeb, 0x9b, 0x8f, 0x81, 0x97, 0xd7, 0x44, 0x1b, 0xfc, 0x39, 0xfc, 0x5f, 0xa6,
	0xab, 0x69, 0xd9, 0x8f, 0x26, 0xf4, 0x65, 0x7c, 0xc8, 0x59, 0xb3, 0x50, 0xda, 0x15, 0x94, 0x4b,
	0x18, 0x64, 0x24, 0x35, 0xcc, 0x3f, 0x9b, 0xa9, 0xe7, 0x7b, 0x37, 0xba, 0xfb, 0xf7, 0xd0, 0x13,
	0x18, 0xe6, 0x28, 0x35, 0xd4, 0x5f, 0xa0, 0xbf, 0x88, 0x55, 0xb4, 0x17, 0xe5, 0xb8, 0x84, 0x41,
	0x16, 0xbb, 0x06, 0x22, 0x02, 0x10, 0x2a, 0xdc, 0x53, 0xd9, 0x88, 0x4f, 0xf1, 0x1c, 0x7a, 0x3a,
	0x5f, 0x0d, 0xd6, 0x57, 0xe8, 0xaf, 0x15, 0x26, 0x7f, 0xdd, 0x4f, 0x07, 0xba, 0x89, 0x7b, 0xfb,
	0x21, 0xfd, 0x49, 0xc6, 0x56, 0xd8, 0x9b, 0x2b, 0x94, 0x65, 0xd8, 0x8e, 0xf2, 0xe2, 0xd7, 0x7f,
	0x70, 0x52, 0x2c, 0x49, 0xf6, 0x1a, 0x8e, 0x96, 0x28, 0xd9, 0xe3, 0xe9, 0x1f, 0x6b, 0x72, 0x5a,
	0xee, 0x48, 0xe7, 0x6c, 0xd3, 0xb5, 0xc9, 0xc5, 0x1b, 0xec, 0x0a, 0x3a, 0x66, 0xbf, 0xb0, 0x31,
	0xed, 0x5b, 0x4e, 0xa0, 0xf3, 0x74, 0x8b, 0x47, 0x11, 0xf0, 0x2d, 0x1c, 0xa7, 0xbb, 0x82, 0x51,
	0xa9, 0xad, 0xfd, 0xe4, 0x3c, 0xd9, 0x78, 0x6f, 0x87, 0x4a, 0xd5, 0x9d, 0x0c, 0x65, 0xed, 0x19,
	0x32, 0x94, 0xbd, 0x16, 0xcc, 0x33, 0x8d, 0x1a, 0x93, 0xcf, 0xac, 0xec, 0x06, 0xf2, 0x99, 0x55,
	0x29, 0xe7, 0x8d, 0xb4, 0xfe, 0x1e, 0x06, 0x64, 0xfd, 0x4b, 0x31, 0x27, 0xeb, 0x6f, 0xe9, 0x32,
	0x6f, 0xb0, 0x8f, 0xd0, 0xcd, 0x25, 0x91, 0x71, 0xc2, 0xfb, 0x9e, 0x3c, 0x3b, 0xcf, 0xb6, 0xfa,
	0x14, 0x61, 0xdf, 0x41, 0x5b, 0x4b, 0x16, 0xa3, 0x6a, 0x63, 0xcb, 0xaa, 0x33, 0xde, 0xec, 0x60,
	0x57, 0xcf, 0x68, 0x09, 0xa3, 0xbd, 0x2d, 0xc5, 0x23, 0xab, 0x57, 0x15, 0x22, 0x83, 0xa7, 0x65,
	0x81, 0xc4, 0xb3, 0xc5, 0x88, 0xc4, 0xab, 0x28, 0x8a, 0xe9, 0x85, 0x50, 0x21, 0xd9, 0x8b, 0x52,
	0x53, 0xc8, 0x5e, 0x58, 0x12, 0x60, 0xa8, 0xf4, 0x28, 0x92, 0x54, 0xb6, 0x0c, 0x90, 0x54, 0x95,
	0x29, 0xe6, 0x8d, 0x79, 0x47, 0xff, 0x8f, 0x7d, 0xf9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x49,
	0xac, 0xac, 0xda, 0x0a, 0x00, 0x00,
}
